--CREAR BASE DE DATOS CON EL NOMBRE dbElectrodomesticos

DROP DATABASE IF EXISTS  dbElectrodomesticos
go
CREATE DATABASE dbElectrodomesticos
go
USE dbElectrodomesticos;
-- CREAR TABLA CLIENTE
CREATE TABLE CLIENTE (
    CODCLI Char(4)  NOT NULL,
    NOMCLI varchar(60)  NOT NULL,
    APECLI varchar(80)  NOT NULL,
    EMACLI Varchar(80)  NOT NULL,
    CELCLI Char(9)  NOT NULL,
    DIRCLI varchar(70)  NOT NULL,
    ESTCLI Char(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY  (CODCLI)
);

-- CREAR TABLA COMPRA
CREATE TABLE COMPRA (
    CODCOM char(5)  NOT NULL,
    FECCOM datetime  NOT NULL,
    CODVEND Char(4)  NOT NULL,
    CODPROV Char(5)  NOT NULL,
    ESTCOM Char(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT COMPRA_pk PRIMARY KEY  (CODCOM)
);

-- CREAR TABLA  COMPRADETALLE
CREATE TABLE COMPRADETALLE (
    IDCOMDET char(5)  NOT NULL,
    CODPRO char(5)  NOT NULL,
    CODCOM char(5)  NOT NULL,
    CANTPRO int  NOT NULL,
    CONSTRAINT COMPRADETALLE_pk PRIMARY KEY  (IDCOMDET)
);

-- CREAR TABLA PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO char(5)  NOT NULL,
    DESCPRO varchar(80)  NOT NULL,
    CATPRO Char(1)  NOT NULL,
    PREPRO decimal(8,2)  NOT NULL,
    STOCKPRO Int  NOT NULL,
    ESTPRO Char(1) DEFAULT 'A'  NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY  (CODPRO)
);

-- CREAR TABLA PROVEEDOR
CREATE TABLE PROVEEDOR (
    CODPROV Char(5)  NOT NULL,
    RAZSOCPROV Varchar(90)  NOT NULL,
    RUCPROV varchar(11)  NOT NULL,
    EMAPROV Varchar(70)  NOT NULL,
    ESTPROV Char(1) DEFAULT 'A'  NOT NULL,
    CONSTRAINT PROVEEDOR_pk PRIMARY KEY  (CODPROV)
);

-- CREAR TABLA VENDEDOR
CREATE TABLE VENDEDOR (
    CODVEND Char(4)  NOT NULL,
    NOMVEND varchar(60)  NOT NULL,
    APEVEND varchar(80)  NOT NULL,
    EMAVEND Varchar(80)  NOT NULL,
    CELVEND Char(9)  NOT NULL,
    DIRVEND varchar(70)  NOT NULL,
    ESTVEND Char(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT VENDEDOR_pk PRIMARY KEY  (CODVEND)
);

-- CREAR TABLA VENTA
CREATE TABLE VENTA (
    CODVEN char(5)  NOT NULL,
    FECVEN datetime   NOT NULL,
    CODCLI Char(4)  NOT NULL,
    CODVEND Char(4)  NOT NULL,
    ESTVEN char(4)  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY  (CODVEN)
);

-- CREAR TABLA VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    IDVENDET int  NOT NULL,
    CODPRO char(5)  NOT NULL,
    CODVEN char(5)  NOT NULL,
    CANTPRO int  NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY  (IDVENDET)
);

-- foreign keys
--  COMPRADETALLE_COMPRA (TABLA: COMPRADETALLE)
ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRADETALLE_COMPRA
    FOREIGN KEY (CODCOM)
    REFERENCES COMPRA (CODCOM);

--  COMPRADETALLE_PRODUCTO (TABLA: COMPRADETALLE)
ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRADETALLE_PRODUCTO
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO (CODPRO);

--  COMPRA_PROVEEDOR (TABLA: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_PROVEEDOR
    FOREIGN KEY (CODPROV)
    REFERENCES PROVEEDOR (CODPROV);

--   COMPRA_VENDEDOR (TABLA: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_VENDEDOR
    FOREIGN KEY (CODVEND)
    REFERENCES VENDEDOR (CODVEND);

--   VENTA_CLIENTE (TABLA: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (CODCLI)
    REFERENCES CLIENTE (CODCLI);

--   VENTA_DETALLE_PRODUCTO (TABLA: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_PRODUCTO
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO (CODPRO);

--   VENTA_DETALLE_VENTA (TABLA: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (CODVEN)
    REFERENCES VENTA (CODVEN);

--  VENTA_VENDEDOR (TABLA: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_VENDEDOR
    FOREIGN KEY (CODVEND)
    REFERENCES VENDEDOR (CODVEND);
-----------REGISTRO DE CLIENTE
INSERT INTO CLIENTE
(CODCLI,NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI)
VALUES
     ('CL01','Juana','Campos Ortíz','Juana.campos@gmail.com','987485152','Av. Miraflores'),
           ('CL02','Sofía','Barrios Salcedo','sofia.barrios@outlook.com','','Jr. Huallaga'),
           ('CL03','Claudio','Pérez Luna','claudio.perez@outlook.com','984512147','Av. Libertadores'),
           ('CL04','Marcos','Ávila Manco','marcos.avila@yahoo.com','','Calle Huallaga'),
           ('CL05','Anastasio','Salomon Inti','anastasio.salomon@gmail.com','','Jr. San Martín')
GO
SELECT * FROM VENDEDOR

-----------REGISTRO DE VENDEDOR
INSERT INTO VENDEDOR
(CODVEND,NOMVEND,APEVEND,EMAVEND,CELVEND,DIRVEND)
VALUES
  ('VEN1','Gloria','Carrizales Paredes ','gloria.carrizales@gmail.com ','984574123 ','Calle Las Begonias'),
  ('VEN2','Gabriel ','Lozada Lombardi ','gabrieLlorada@gmail.com ','974512368 ','Av. Los Grasoles'),
  ('VEN3','Gilberto','Martinez Guerra ','giiberto.martinez@gmail.com ','','Jr. Palomares')
GO

SELECT * FROM VENDEDOR

-----------REGISTRO DE PROEEVEDOR
INSERT INTO PROVEEDOR
           (CODPROV,RAZSOCPROV,RUCPROV,EMAPROV)
     VALUES
           ('PRV01','LG Corportation',87542136951,'informes@lg.com.pe'),
           ('PRV02','SONY',45213698741,'informes@sony.com.pe'),
           ('PRV03','SAMSUN',85321697661,'informes@samsung.com.pe'),
           ('PRV04','OSTER SRL',55663214478,'informes@oster.com.pe'),
           ('PRV05','ASUS',99663325478,'informes@asus.com.pe')
GO

SELECT * FROM PROVEEDOR
-----------REGISTRO DE  PRODUCTO
CREATE PROCEDURE InsertDatesProducto

AS
INSERT INTO PRODUCTO
           (CODPRO,DESCPRO,CATPRO,PREPRO,STOCKPRO)
     VALUES
           ('PRO01','Refrigeradora LG Side By Side',1,4149,15),
           ('PRO02','Refrigeradora SBS 602L',1,3599,10),
           ('PRO03','Refrigeradora Top Mount 500 L',1,2799,8),
           ('PRO04','TV SAMSUNG UHD 55"',2,1799,25),
           ('PRO05','Televisor 65" LG UHD 4K',2,2999,20),
           ('PRO06','TV CRYSTAL UHD 55',2,2299,7),
           ('PRO07','ASUS X415JA Core i3 10a Gen 14"',3,1099,17),
           ('PRO08','Lenovo Idea Pad 5i Intel Core i7 14"',3,3099,10),
           ('PRO09','Laptop HP 15-dw1085la Intel Core i3',3,1600,15),
           ('PRO10','Galaxy A52 128GB',4,1200,25),
           ('PRO11','iPhone 11 64GB Morado',4,2600,30),
           ('PRO12','Poco X3 GT 5G 256GB 8GB',4,1450,20)
GO
EXEC InsertDatesProducto
SELECT * FROM PRODUCTO


